version: '3.8'
services:
  mongodb:
   container_name: mongo
   volumes:
    - ./backend/data:/data
    ports:
    - "27017:27017"

   backend:
    container_name: backend
    build: ./backend
    env_files: 
     - ./backend/.ev.sample
     ports:
     - "5000:5000"
     depends_on:	
      - mongodb

    frotend:
     container_name: frontend
     build: ./frontend
     env_files: 
      - ./backend/.ev.sample
      ports:
      - "5173:5173"
      depends_on:	
       - mongodb

volumes:
  data:
